name: Push changes to shared repository

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set Git identity
      run: |
        git config --global user.email "rares.lemnariu@ro.bosch.com"
        git config --global user.name "BFMC - Rares Lemnariu"

    - name: Fetch remote data branch
      run: |
        git remote add shared git@github.com:ECC-BFMC/Shared.git
        git fetch shared data
  
    - name: Merge remote data branch into local subtree
      run: |
        git checkout -b temp-branch
        git subtree add --prefix=src/data shared data --squash || echo "subtree already exists"
        git subtree pull --prefix=src/data shared data --squash || echo "no need to pull"

    - name: Resolve conflicts by prioritizing local changes
      run: |
        git add src/data
        git commit -m "Resolve conflicts by keeping local changes" --allow-empty

    - name: Push merged changes to remote data branch
      run: |
        git subtree push --prefix=src/data shared data

    - name: Cleanup
      run: |
        git checkout master
        git branch -D temp-branch

    - name: Dispatch event to shared repository
      run: |
        response=$(curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ECC-BFMC/Shared/actions/workflows/triggerPullData.yml/dispatches \
          -d '{"ref":"main", "inputs": {"project_name": "Brain"}}'')
        echo "Response: $response"




