name: Push changes to subtree

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set Git identity
      run: |
        git config --global user.email "rares.lemnariu@ro.bosch.com"
        git config --global user.name "BFMC - Rares Lemnariu"
    
    - name: Fetch all branches and tags
      run: git fetch --all --tags
  
    - name: Split the subtree
      id: split
      run: git subtree split --prefix=src/data -b temp-branch
      continue-on-error: true

    - name: Check if split was successful
      run: |
        if git show-ref --verify --quiet refs/heads/temp-branch; then
          echo "Subtree split successful."
        else
          echo "Subtree split failed. Exiting."
          exit 1
        fi

    - name: Force-push local changes to subtree
      if: success()
      run: |
        git push -f git@github.com:ECC-BFMC/Shared.git temp-branch:data

    - name: Cleanup local temp-branch
      if: success()
      run: git branch -D temp-branch