name: Propagate changes to data projects

on: 
  push:

jobs:
  identify-and-print:
    runs-on: ubuntu-latest

    steps:
      - name: Check for project_name in push payload
        id: check-project-name
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"project_name="* ]]; then
            project_name=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*project_name=\([^ ]*\).*/\1/p')
            echo "Project Name from commit message: $project_name"
            echo "::set-output name=project_name::$project_name"
          else
            echo "No project_name found in commit message."
            echo "::set-output name=project_name::None"
          fi         
    
  dispatch:
    needs: identify-and-print
    runs-on: ubuntu-latest
    if: success()
    outputs:
      project_name: ${{ steps.check-project-name.outputs.project_name }}

    steps:
      - name: Set up repository dispatch parameters and dispatch events
        run: |
          project_name="${{ env.project_name }}"
          
          repositories=(Brain CompetitionPCing)

          # Remove the project_name from the repositories array
          for i in "${!repositories[@]}"; do
            if [[ "${repositories[$i]}" == "$project_name" ]]; then
              unset 'repositories[i]'
            fi
          done

          echo "Repos to update: ${repositories[@]}"

          # # Uncomment the following block to perform the actual dispatch
          # # for repo in "${repositories[@]}"; do
          # #   echo "Dispatching event to repository: $repo"
          # #   gh api repos/"$repo"/dispatches \
          # #     -f event_type=update-subtree-$project_name \
          # #     -f client_payload='{}' \
          # #     -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}"
          # # done

          # # Print the dispatch information
          # for repo in "${repositories[@]}"; do
          #   echo "Prepared to dispatch event to repository: $repo"
          #   echo "Event type: update-subtree-$project_name"
          #   echo "Would use token: ${{ secrets.REPO_ACCESS_TOKEN }}"
          # done
